name: carrot market server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        shell: bash
        
      - name: Make Directory
        run: mkdir -p deploy
        
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy
      
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      - name: Copy script
        run: cp ./scripts/*.sh ./deploy
        
      - name: Grant execute permission for deploy.sh
        run: chmod +x ./scripts/deploy.sh
        shell: bash

      - name: Make Zip File
        run: zip -r ./carrot-market.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./carrot-market.zip s3://${{ secrets.S3_BUCKET_NAME }}/
      
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name carrot-market \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name carrot-market-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=carrot-market.zip \
          --region ap-northeast-2
